implement list
CPP-KT/intrusive_list_task pull request #1
Opened 2020-09-12 12:28 UTC by kp2pml30

Кирилл Прокопенко M3236

2020-09-12 19:15 UTC, Tindarid commented on intrusive_list.h
> +        }
А ты уверен что это желаемое поведение?

2020-09-12 19:17 UTC, Tindarid commented on intrusive_list.h
> +        list_element<Tag> *root = new list_element<Tag>;
А нужно ли тебе тут `new`? Почему бы не хранить не указатель, а саму структуру

2020-09-12 19:19 UTC, Tindarid commented on intrusive_list.h
> +                return static_cast<IT&>(*me);
`assert` это полезно

Но они нужны чтобы проверять свои собственные инварианты

Например, ты сделал какую-то операцию, которая гарантированно увеличила `size()` на 1. В конце этой операции ты можешь сделать `assert(prev_size + 1 == size()`

В данном случае лучше гарантировать UB (относится ко всем строчкам кода, где фигурируют ассерты)

2020-09-12 19:20 UTC, Tindarid commented on intrusive_list.h
> +            clear();
?

2020-09-12 19:22 UTC, Tindarid commented on intrusive_list.h
> +        }
Сложно. Может быть сделаем это через `splice`?

2020-09-12 19:25 UTC, Tindarid commented on intrusive_list.h
> +        }
Давай выразим через `insert`

2020-09-12 19:25 UTC, Tindarid commented on intrusive_list.h
> +        }
Давай выразим через `insert`

2020-09-12 19:26 UTC, Tindarid requested changes
В целом все норм, кроме `clear` :)

2020-09-12 20:20 UTC, kp2pml30 commented on intrusive_list.h
> +        list_element<Tag> *root = new list_element<Tag>;
Если просто убрать указатель, то будет проблема с тем, что если будет не `new`, то, например, в `const_iterator begin() const noexcept` будет `const root`, от которого указатель на константу. И тогда нужны плохие касты, или другие хаки.

2020-09-12 20:51 UTC, kp2pml30 commented on intrusive_list.h
> +        list_element<Tag> *root = new list_element<Tag>;
Поправил остальное

2020-09-13 09:46 UTC, kp2pml30 commented on intrusive_list.h
> +                return static_cast<IT&>(*me);
Я посмотрел как сделан `vector::pop_back` (и другие его функции):
```
00388 void
00389 pop_back()
00390 {
00391 __glibcxx_check_nonempty();
00392 this->_M_invalidate_if(_Equal(--_Base::end()));
00393 _Base::pop_back();
00394 }
```
И они используют свои ассерты:
```
_GLIBCXX_DEBUG_VERIFY(! this->empty(), \
  _M_message(::__gnu_debug::__msg_empty) \
  ._M_sequence(*this, "this"))
```
Мне кажется, что `assert` помогает в дебаге кода. Его не отлавливают, и он гарантирует то же UB в релизе.

2020-09-13 17:12 UTC, Tindarid commented on intrusive_list.h
> +        }
Я имел ввиду, что у тебя элементы внутри листа остаются в странном состоянии.
Они как бы связаны между собою, но ты эту связь использовать не можешь (т.е. они как будто где-то находятся, но на самом деле нет)

2020-09-13 17:16 UTC, Tindarid commented on intrusive_list.h
> +        list_element<Tag> *root = new list_element<Tag>;
А так ты получаешь лишний уровень косвенности и у тебя теряются гарантии для конструктора

Можешь почитать про ключевое слово `mutable`, но я не совсем понял где здесь проблема с `const`-нтностью

2020-09-13 17:16 UTC, Tindarid requested changes
`clear` again

2020-09-13 17:57 UTC, kp2pml30 commented on intrusive_list.h
> +        list_element<Tag> *root = new list_element<Tag>;
Насколько я знаю, `const_iterator` при `->`, `*` должен давать `const T&`, но при этом сам итератор имеет право изменяться (что несколько абсурдно в случае когда `next` и `prev` лежат внутри этого же `const T&`), это подтверждается шапкой данной мне свыше: `iterator insert(const_iterator pos, T& u) noexcept`, функция обязана изменить `pos->prev`.
Таким образом, iterator должен хранить всегда `list_element<Tag>*`, а не `std::conditional_t<std::is_const_v<IT>, const list_element<Tag>, list_element<Tag>>*`. Тогда появляется проблема в методе
```
        const_iterator end() const noexcept
        {
            return const_iterator(&root);
        }
```
он получает `const this`, в котором `const root` => `decltype(&root) == const list_element<Tag>*`[&], но если он лежит не внутри объекта, то мы имеем константный указатель, а не указатель на константу.
Добавление поля-указателя, которое показывает на `root`, `const_cast`, `mutable` - это все обман системы типов

2020-09-14 18:51 UTC, Tindarid reviewed
Ок

2020-09-14 18:52 UTC, closed without merging