Add task implementation
CPP-KT/intrusive_list_task pull request #3
Opened 2020-09-12 19:31 UTC by NH5pml30

2020-09-12 19:45 UTC, Tindarid commented on intrusive_list.h
> +    }
А что с элементами внутри листа будет?

2020-09-12 19:49 UTC, Tindarid commented on intrusive_list.h
> +    }
`insert`?

2020-09-12 19:49 UTC, Tindarid commented on intrusive_list.h
> +    }
`insert`?

2020-09-12 19:50 UTC, Tindarid commented on intrusive_list.h
> +    }
`unlink`?

2020-09-12 19:50 UTC, Tindarid commented on intrusive_list.h
> +    }
Копипаста

Может быть лучше через `splice`?

2020-09-12 19:57 UTC, Tindarid requested changes
Все почти норм, кроме `clear`

2020-09-12 20:24 UTC, NH5pml30 commented on intrusive_list.h
> +    }
Добавил цикл с занулением ссылок на соседей

2020-09-12 20:24 UTC, NH5pml30 commented on intrusive_list.h
> +    }
Заменил

2020-09-12 20:25 UTC, NH5pml30 commented on intrusive_list.h
> +    }
Да

2020-09-12 20:25 UTC, NH5pml30 commented on intrusive_list.h
> +    }
Да

2020-09-12 20:25 UTC, NH5pml30 commented on intrusive_list.h
> +    }
Сделал

2020-09-13 17:06 UTC, Tindarid reviewed
OK

2020-09-13 17:07 UTC, closed without merging