Development
CPP-KT/intrusive_list_task pull request #4
Opened 2020-09-13 16:45 UTC by paskudnicc

Plz check

2020-09-13 17:20 UTC, Tindarid commented on intrusive_list.h
> +            }
А что с `prev` и `next`? Они указывают на какую-то странную память теперь

2020-09-13 17:22 UTC, Tindarid commented on intrusive_list.h
> +            }
А давай сделаем конструктор приватным, чтобы нельзя было сделать итератор от `nullptr`

2020-09-13 17:23 UTC, Tindarid commented on intrusive_list.h
> +            }
А, он уже сделан. Тогда эта проверка бессмысленна

2020-09-13 17:25 UTC, Tindarid commented on intrusive_list.h
> +        }
Что?)

2020-09-13 17:25 UTC, Tindarid commented on intrusive_list.h
> +        }
Подумай, может быть `splice`?

2020-09-13 17:26 UTC, Tindarid commented on intrusive_list.h
> +
А что будет с элементами листа? Они ведь будут как-будто в каком-то листе

2020-09-13 17:27 UTC, Tindarid commented on intrusive_list.h
> +
Эти функции отлично выражаются через `insert` и `erase`

2020-09-13 17:27 UTC, Tindarid commented on intrusive_list.h
> +            }
Эти тоже

2020-09-13 17:43 UTC, Tindarid requested changes
.

2020-09-13 18:01 UTC, paskudnicc commented on intrusive_list.h
> +            }
Ну почти бессмысленна. Эта проверка добавляла фичи

2020-09-13 18:01 UTC, paskudnicc commented on intrusive_list.h
> +        }
Действительно

2020-09-13 18:03 UTC, paskudnicc commented on intrusive_list.h
> +            }
На самом деле в моем листе я готов к такому, а так согласен - лучше обнулять

2020-09-13 18:06 UTC, paskudnicc commented on intrusive_list.h
> +
Всё так

2020-09-13 18:07 UTC, paskudnicc commented on intrusive_list.h
> +
В смысле, они перевязаны ссылками? А почему это наша проблема?

2020-09-14 18:55 UTC, Tindarid commented on intrusive_list.h
> +            }
Кажется ты тут что-то перепутал

2020-09-14 18:56 UTC, Tindarid commented on intrusive_list.h
> +
Ладно, пусть будет так

2020-09-14 18:56 UTC, Tindarid reviewed
Ок

2020-09-14 19:04 UTC, closed without merging