first solution
CPP-KT/intrusive_list_task pull request #5
Opened 2020-09-13 17:23 UTC by GEN05

2020-09-14 18:59 UTC, Tindarid commented on intrusive_list.h
> +        }
Непонятен твой инвариант

Элемент не содержащийся в листе, его `prev` и `next` указывают на `nullptr`, если он был выкинут из листа, и на себя, если его просто создали

2020-09-14 19:00 UTC, Tindarid commented on intrusive_list.h
> +            }
А зачем уметь конструироваться от итератора на другой тип?

2020-09-14 19:01 UTC, Tindarid commented on intrusive_list.h
> +        }
А давай без выделения памяти

2020-09-14 19:02 UTC, Tindarid commented on intrusive_list.h
> +    };
Название функции не соотвествует содержанию

2020-09-14 19:08 UTC, Tindarid commented on intrusive_list.h
> +        }
Какие-то странные хаки по поводу прыжков туда-сюда по памяти

2020-09-14 19:09 UTC, Tindarid commented on intrusive_list.h
> +        }
выражается через `insert`

2020-09-14 19:09 UTC, Tindarid commented on intrusive_list.h
> +        }
Это тоже выражается через `insert`

2020-09-14 19:11 UTC, Tindarid requested changes
Нет реализации `clear`

2020-09-19 00:39 UTC, GEN05 commented on intrusive_list.h
> +        }
fix

2020-09-19 00:52 UTC, GEN05 commented on intrusive_list.h
> +            }
Чтобы уметь преобразовывать `const` `iterator` в не `const`. Как оказалось, для тестов надо это уметь делать.

2020-09-24 21:01 UTC, closed without merging