Do
CPP-KT/intrusive_list_task pull request #6
Opened 2020-09-14 06:35 UTC by NelosG

2020-09-14 08:42 UTC, StarOrpheus commented on intrusive_list.h
> +#include <xtr1common>
nice include

2020-09-14 19:20 UTC, Tindarid commented on intrusive_list.h
> +                head.next->unlink();
`pop_back()`

2020-09-14 19:25 UTC, Tindarid commented on intrusive_list.h
> +        }
Когда элемент не `linked`, чему равны его `prev` и `next`?

2020-09-14 19:26 UTC, Tindarid commented on intrusive_list.h
> +    };
ПОчему этот конструктор не `private`?

2020-09-14 19:31 UTC, Tindarid commented on intrusive_list.h
> +        }
Почему `move-ctor` и `move-assignment-operator` по разному реализованы?

2020-09-14 19:32 UTC, Tindarid requested changes
.

2020-09-14 19:46 UTC, NelosG commented on intrusive_list.h
> +        }
nullptr, а чему должны быть?

2020-09-14 20:12 UTC, NelosG commented on intrusive_list.h
> +#include <xtr1common>
Исправил

2020-09-14 20:13 UTC, NelosG commented on intrusive_list.h
> +                head.next->unlink();
Исправил

2020-09-14 20:13 UTC, NelosG commented on intrusive_list.h
> +    };
Исправил

2020-09-14 20:13 UTC, NelosG commented on intrusive_list.h
> +        }
Исправил

2020-09-14 20:24 UTC, NelosG commented on intrusive_list.h
> +        }
исправил

2020-09-15 12:49 UTC, Tindarid commented on intrusive_list.h
> +        }
maybe `std::advance`

2020-09-15 13:00 UTC, Tindarid reviewed
Ok

2020-09-15 18:29 UTC, closed without merging